# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontrol.proto\x12\x07\x63ontrol\"\x12\n\x05State\x12\t\n\x01x\x18\x01 \x01(\x01\"\x17\n\nPrediction\x12\t\n\x01y\x18\x01 \x01(\x01\x32\x44\n\nControlAPI\x12\x36\n\rGetPrediction\x12\x0e.control.State\x1a\x13.control.Prediction\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATE._serialized_start=26
  _STATE._serialized_end=44
  _PREDICTION._serialized_start=46
  _PREDICTION._serialized_end=69
  _CONTROLAPI._serialized_start=71
  _CONTROLAPI._serialized_end=139
# @@protoc_insertion_point(module_scope)
