services:
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - iot
    volumes:
      - ./mosquitto_config:/mosquitto/config

  influxdb:
    image: influxdb:2.7.1
    hostname: influxdb
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    networks:
      - iot
    volumes:
      - influxdb-config:/etc/influxdb2
      - influxdb-data:/var/lib/influxdb2
      - ./influx_scripts:/docker-entrypoint-initdb.d
    env_file:
      - common.env
      - influxdb.env

  telegraf:
    image: telegraf
    hostname: telegraf
    container_name: telegraf
    restart: always
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - iot
    volumes:
      - ./telegraf_config/mqtt_telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - common.env

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - hass-data:/config
      - /etc/localtime:/etc/localtime:ro

networks:
  iot:

volumes:
  influxdb-config:
  influxdb-data:
  hass-data: